object TwitterKeyHolder {
  val CONSUMER_KEY_KEY = "ZCoxHCZ1luAHbVbSSCNMdA9zh"
  val CONSUMER_SECRET_KEY = "pQGXCMKkHeXBSbgLTTNLWPBvdEKjIzqECQbqhNtSZPfJNEpuzu"
  val ACCESS_TOKEN_KEY = "1009523479-JPYUa9nRqKTNRkYxJkl8jQ52pypJHapwNNuxUde"
  val ACCESS_TOKEN_SECRET_KEY = "n9vJwFGx9YKS5Rr3i7qrSBePYARdxLB9MRI1JcKb81IAB"
}